### ISSUE TITLE
two small things (working on FreeBSD12-RELEASE with clang 6.0.1)

### ISSUE THREAD

**Issue by sawdustdood** [ColumPaget/pam_ihosts#1]
Won't compile with straight clone.  The `Makefile.in` appears to need to be updated with:
  `$(CC)` rather than an explicit call to `gcc`
and need to add:
  `#include <netinet/in.h>`
to `utility.h` because sockaddr_in is in a different location in FreeBSD.
I'm super-noob, so I'm not sure the best way to do the latter, but I would imagine this would be in the configure.

**Comment by ColumPaget** [comment]
Thanks for this! These changes are in the latest release, which now builds under macosx too! (probably also other BSDs).
